name: Lab 3 Create Artifact
#Trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#Job
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    #Checkout our repo
    - uses: actions/checkout@v3

    #Use Node
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Pretend to build
      run: echo Pretending to build some kind of app...
    - name: Push artifact foo.txt
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: foo.txt